### ISSUE TITLE
GObject property binding

### ISSUE THREAD

**Issue by fludardes** [gtk-rs/glib#166]
Sorry, it seems that safe Rust version of [g_object_bind_property](https://developer.gnome.org/gobject/stable/GBinding.html#g-object-bind-property) and other property binding functions are currently missing...

**Comment by ian-p-cooke** [comment]
is work on adding these functions planned?  I find them useful for binding GObjects to properties from a Glade file.

**Comment by sdroege** [comment]
This should be relatively easy to add, but needs manual FFI code to be added to glib/src/object.rs (into the ObjectExt trait and its generic impl). Instead of the `_full` function, the `_with_closures` one should be taken, apart from that it should all be fine.

If someone wants to work on this and has any questions about how after reading the existing code in glib/src/object.rs, I'd be happy to help

**Comment by GuillaumeGomez** [comment]
If this issue isn't fixed in two weeks (or so), I'll try to get a look. But I'd prefer if someone else worked on it.

**Comment by sdroege** [comment]
@GuillaumeGomez This can be closed now since quite a while :)

**Comment by GuillaumeGomez** [comment]
Indeed!
