### ISSUE TITLE
Impl Variant for library user types

### ISSUE THREAD

**Issue by Martin1887** [gtk-rs/glib#339]
Hello.

I am trying to write a frontend for Xi editor in GTK using Rust, but I have found no manner of sending own structs instances to actions.

For instance, I have an action to open a new tab, so I need the notebook reference to add a tab in that object.

I use actions (`SimpleAction`) in order to have commands in the application whose shortcut can be modified by the user.

Maybe there are other forms of achieving this task, but I have not found them.

Any recommendations about this? If a better manner does not exist, any hints about implementing `Variant` for custom structs?

Thanks and regards.

**Comment by GuillaumeGomez** [comment]
Actions take closures as parameter. Closures can use any "outside" type you want, so I'm not sure to understand your issue in here...

**Comment by sdroege** [comment]
It's not possible to implement `GVariant` for custom types (it must be one of the types supported inside GLib for `GVariant`, or combinations of those), but with `GValue` that is possible. And actually nowadays you can already store any kind of Rust struct inside an `glib::AnyValue` which can be stored inside a `glib::Value` and can be retrieved again via `std::Any`'s downcast mechanism.

Does that help? Otherwise some more details about what you're trying to achieve would be useful :)

**Comment by Martin1887** [comment]
I'm using `SimpleAction` for these tasks. The `SimpleAction::new` function has the following signature:
```
pub fn new<'a, P: Into<Option<&'a VariantTy>>>(
    name: &str, 
    parameter_type: P
) -> SimpleAction
```
And the `SimpleActionExt::connect_activate` function has the following signature:
```
fn connect_activate<F: Fn(&Self, &Option<Variant>) + 'static>(
    &self, 
    f: F
) -> SignalHandlerId
```

Using this mechanism, the function called when the `SimpleAction` is fired only can be a function that receives a `SimpleAction` reference and an optional `Variant` parameter. This is the reason why I need the conversion of structs to `Variant`.

But if you know better and more flexible flows that allow do the same thing without this problem I will use them 😁.

**Comment by sdroege** [comment]
You have to serialize your structs into something that can be stored in a `GVariant`. The actions are potentially sent between processes and as such need to be serializable (which is the whole point of `GVariant`).

**Comment by Martin1887** [comment]
Do you mean for instance following the next workflow?

1. Serialize the object into JSON using `serde_json`, store the result in a `&str` and convert it into `Variant`.
2. In the action function deserialize the JSON and call functions on it.
3. In the action function invoke a special callback that receives the object and assigns it to the GTK tree.

I see this workflow too much complicated. In addition, the performance of dropping a container for another one (for instance removing a `Notebook` for the modified `Notebook` with a new tab) cannot be good, with a really bad user experience.

Maybe I have not understood you, or maybe other better alternatives that I don't know exist.


Thanks for your assistance.

**Comment by sdroege** [comment]
What you described would work, yes. But if you look at `GVariant`, it basically allows storing something like JSON directly. It's a serialization format by itself already, just binary instead of textual like JSON (and there's no serde support for it yet, you would have to do the serialization manually currently).

I'd suggest reading the `GVariant` C documentation, it has a very good explanation of how `GVariant` works. The important part to keep in mind here is that you must somehow serialize your data as the action stuff (and most of the `GApplication` API) passes (or can pass) data between processes.

----

Writing serde support for `GVariant` should be relatively simple and a nice task :)
