### ISSUE TITLE
GString: erroneous string copies in current implementation

### ISSUE THREAD

**Issue by philn** [gtk-rs/glib#422]
```
[13:17:42] <slomo> philn: From<GString> for String currently copies the CString (in case of ForeignOwned), instead of just converting the CString into a String without copying
[13:18:57] <slomo> philn: similarly impl From<String> for GString can probably also happen without copying
```

**Comment by philn** [comment]
> similarly impl From<String> for GString can probably also happen without copying

I think that's fine because that impl uses `String::as_bytes()` vector which chains to `From<Vec<u8>>` which chains to `From<CString>` which creates a ForeignOwned already.

**Comment by sdroege** [comment]
> I think that's fine because that impl uses `String::as_bytes()` vector which chains to `From<Vec<u8>>` which chains to `From<CString>` which creates a ForeignOwned already.

`String::as_bytes()` returns a reference and does not consume the string. So that would require the `CString` to take a copy.

You probably want `String::into_bytes()` instead? That would consume the `String`, return a `Vec<u8>` and that can then be directly taken from the `CString` for its construction.

**Comment by philn** [comment]
Right, PR updated :)
