### ISSUE TITLE
Allow subtypes to specialize the Debug formatting

### ISSUE THREAD

**Issue by heftig** [gtk-rs/glib#435]
It would be nice if subtypes (e.g. `GstObject`) could specialize the formatting of the `Debug` trait.

A possible approach would be for glib-rs to define a `GRsDebug` GInterface with a formatter method and implement it for `GObject`. `glib::object::Object`'s `Debug` impl would then call this interface. The interface implementation can be overridden by subclasses as needed.

**Comment by sdroege** [comment]
This would also be useful for things like `GInetAddress` and the like that could print something more useful (the actual IP) than they do now. And we could probably extend this to other traits than `Debug` too (`Hash`, `Eq`, `Ord`, ...?).

The problem we currently have is that we need dynamic dispatch for implementing these traits in a consistent way, or otherwise the same object would give different result based on whether it was cast to e.g. a `gst::Object` or just a `glib::Object`. Traits don't provide us with this here but we could go via a custom `GInterface` defined by the bindings that could then be implemented by the corresponding subclasses.

However there's one problem: we can't implement interfaces on types that are already initialized from what I remember.

**Comment by sdroege** [comment]
Yes it's impossible to add interfaces after the class is initialized. Let's close this then.

If anything we would need such an interface added to `GObject` itself then.
