### ISSUE TITLE
SignalHandlerId isn't `Copy`

### ISSUE THREAD

**Issue by hfiguiere** [gtk-rs/glib#565]
SignalHandlerId should be `Copy`

**Comment by sdroege** [comment]
No, it's intentionally not `Copy` so that you can't disconnect the same signal handler twice, which would give you a critical warning from GObject (you can still get one by disconnecting from the wrong object but that's harder to prevent).

You probably want to put your signal handler ids into an `Option` and when disconnecting use `Option::take`.

**Comment by hfiguiere** [comment]
Ah. Make sense.

**Comment by GuillaumeGomez** [comment]
Maybe we should add this into the documentation so people will know.

**Comment by sdroege** [comment]
Sounds good, to you have a suggestion where to put it in the docs?

**Comment by GuillaumeGomez** [comment]
On the type directly I guess?
