### ISSUE TITLE
Confusing FromGlibPtrNone docs

### ISSUE THREAD

**Issue by dcz-purism** [gtk-rs/glib#586]
When trying to create a custom GVariant using `ToVariant::to_variant`, I tried to use `from_glib_ptr_full`, only to see glib criticals due to double-free. As I investigated, I came across the implementation for basic types in https://github.com/gtk-rs/glib/blob/master/src/variant.rs#L260

This implementation, confusingly, returns an owned `Variant`, using `from_glib_ptr_none`.

> FromGlibPtrNone: Translate from a pointer type without taking ownership, transfer: none.

It seems this function is only useful for references here. I looked for something explaining this discrepancy, and I found https://github.com/gtk-rs/glib/blob/master/src/object.rs#L551

> impl FromGlibPtrNone {
> unsafe fn from_glib_none {
> // Attention: This takes ownership of floating references!

This makes it clear that the `Variant` instance returned is actually owned, but on the other hand, it contradicts the documentation for `FromGlibPtrNone`.

I have an impression that `FromGlibPtrNone` actually does more/something else than its documentation says, but I'm not quite sure what it is. I believe the documentation for the translate traits calls for some more details, so that the use cases are clear. It might be useful to explain the "floating references", or make it clear how they are being used in the bindings.

**Comment by EPashkin** [comment]
As Variant use Shared, you better look to it, not to Object.
In  https://github.com/gtk-rs/glib/blob/master/src/shared.rs#L393
[g_variang_ref_sing](https://developer.gnome.org/glib/stable/glib-GVariant.html#g-variant-ref-sink)  called, and it claim floating reference.

**Comment by EPashkin** [comment]
Docs of FromGlibPtrNone show generic case, but floating references add complexity.
And shared types like Variant add its own complexity too.

**Comment by EPashkin** [comment]
Also https://developer.gnome.org/glib/stable/glib-GVariant.html#g-variant-new-boolean etc. says `[transfer none]` too.

**Comment by dcz-purism** [comment]
Thanks for answering.

Does `[transfer none]` relate to `FromGlibPtrNone`? They seem to be completely different:

> don't free data after the code is done

this sounds a lot like "obtain and take ownership", which is what `FromGlibPtrFull` says it does.

If they are the same, then the docs for `FromGlibPtrNone` are wrong, because ownership is actually transferred.

**Comment by EPashkin** [comment]
"take ownership" meant "you must free data after you finished to use or you get memory leak"

**Comment by EPashkin** [comment]
In case referenced types:
for "none" you must just increment reference and decrement it when you done as Giver can use this data after you finished,
for "full" transfer Giver don't use this data anymore and you don't need increment reference, but still need decrement it when you done.

**Comment by dcz-purism** [comment]
Yes, that's taking ownership as I understand it. It means `drop()` can work correctly.

**Comment by dcz-purism** [comment]
> for "none" you must just increment reference and decrement it when you done as Giver can use this data after you finished,
> for "full" transfer Giver don't use this data anymore and you don't need increment reference, but still need decrement it when you done.

That sounds right. `none` is no ownership transfer, and `full` is ownership transfer.

Then there's still the problem with:

> unsafe fn from_glib_none {
> // Attention: This takes ownership of floating references!

So none is *sometimes* ownership transfer, and sometimes not. I think it's a problem that it's not documented when exactly. I am very confused about it.

**Comment by EPashkin** [comment]
We don't documented "ownership transfer" specially because it already documented in glib and we just use its convention: https://developer.gnome.org/programming-guidelines/stable/memory-management.html.en
Also it tough to separate it to docs for `FromGlibPtrNone`, `ToGlibPtrNone` etc. as it need be explained whole.

**Comment by dcz-purism** [comment]
That's not exactly true. You document ownership transfer in this line: https://github.com/gtk-rs/glib/blob/master/src/translate.rs#L1165

> /// Translate from a pointer type without taking ownership, transfer: none.

It is clearly described "without taking ownership", no exceptions. But there are exceptions, and the user has no way of finding them without stuff crashing, or without going to https://developer.gnome.org/programming-guidelines/stable/memory-management.html.en

That makes the "ownership transfer" in the Rust sense wrong in this case, so it should be replaced with the link to GTK docs. What do you think?

**Comment by EPashkin** [comment]
I don't sure that docs can be improved, and have no idea how, as "transfer ownership" used in glib's sense, not Rust's

This mismatch comes from glib anyway: 
https://wiki.gnome.org/Projects/GObjectIntrospection/Annotations#Memory_and_lifecycle_management
"none: the recipient does not own the value"

cc @GuillaumeGomez, @sdroege

**Comment by sdroege** [comment]
> > unsafe fn from_glib_none {
> > // Attention: This takes ownership of floating references!
> 
> So none is _sometimes_ ownership transfer, and sometimes not. I think it's a problem that it's not documented when exactly. I am very confused about it.

Don't worry about being confused about that. Floating references are extremely confusing and unintuitive and generally I recommend people to not break their brain thinking about them. That they exist in GObject is a historical mistake. Note that this only affects GObjects that inherit from `GInitiallyUnowned` (GTK widgets, GStreamer elements mostly).

See at the top here the "Floating References" paragraph for some background: https://developer.gnome.org/gobject/stable/gobject-The-Base-Object-Type.html

So to the actual problem here. Because gobject-introspection is not really extensible it is not possible in the metadata to declare if something takes ownership (`gtk_container_add()`) of a floating reference or returns a floating reference (all widget constructors, for example). As such they are marked as `transfer none` (in the code you can mark them as `transfer floating` but that's only for documentation purposes and in the XML is transformed to `transfer none`, see also all widget constructors returning `transfer none`).

The expected behaviour of bindings now is the following: Whenever a floating reference is retrieved in bindings in the context of `transfer none` then this reference must be sunken and taken ownership of (-> `g_object_ref_sink()`). This means that the bindings now own this reference.

On a C level it also means (which does not affect bindings because of the above): passing a floating reference to a function that takes ownership of floating references (marked `transfer none`), like `gtk_container_add()`, will make this function take ownership of the floating reference.

Now for both cases above, if the object in question is not floating (not a floating reference because something else sunk it before) then it behaves as you would expect from `transfer none`. As a return value we don't own it, so we have to copy/increase the reference count/borrow. As a parameter we don't pass away ownership but if the callee wants to keep a reference/copy it has to do so by itself.

For `transfer full` everything is also as you would expect. As a return value it means that we now own the thing and have to free/unref it again later when we don't need it anymore, as a parameter it means that we pass away ownership so if we want to continue using it afterwards we have to increase the reference count or copy.

The last two paragraphs are how the whole thing works in general and always except for floating references. Floating references on the other hand behave very weird and unintuitive and every few months a new bug is found in one of the language bindings where they are handled incorrectly or C code handling them incorrectly.

Does this answer your questions? :)

If you can condense that into something that fits into the documentation, please submit a PR. I won't do that myself because I'd either end up writing a book and causing more confusing than I would solve, or not write enough like the current documentation and code comments. I'd be happy to review such a PR in any case to make sure your understanding is correct!

**Comment by sdroege** [comment]
Oh and forgot, the above still misses some special cases with floating references in some abstruse situations. For example relating to signal/callback parameters that might be floating, floating references inside `GValue`s and things like that.

That `GVariant` took over the concept of floating references is IMHO unacceptable after all the pain they caused in the past already before `GVariant` was invented. But here we are. Fortunately it's less problematic for `GVariant` because it's less widely used and functions where they appear usually have a very specific "shape".

**Comment by EPashkin** [comment]
Note that `transfer floating` is possible https://wiki.gnome.org/Projects/GObjectIntrospection/Annotations#Memory_and_lifecycle_management:
`floating: alias for none, can be used for floating objects. `
just no one used it 😭

**Comment by sdroege** [comment]
>  just no one used it :sob:

We use it in GStreamer, but as I said above it's only in the C code and docs. Inside the XML file and everywhere else it's directly translated to `transfer none`.

**Comment by dcz-purism** [comment]
> Does this answer your questions? :)

I think it answers most of them. I notice that you wrote

> does not affect bindings

I had a suspicion that the bindings preemptively sink all references and don't handle any floating ones, in order to escape the floating hell. Is that true? That alone would imply a lot of answers regarding ownership handling.

Am I right in understanding that the `from_glib_foo` function family exist primarily to be called immediately as a return value of the corresponding kind is received? I'm asking because I've previously successfully (?) used them to reference preexisting objects across the FFI bounds.

> If you can condense that into something that fits into the documentation, please submit a PR. I won't do that myself because

Sure, I'll create one.
I get what you mean, as someone who just learned the concept, I still have a simple enough understanding of the concept to hit a newcomer's abstraction level.

**Comment by sdroege** [comment]
> I had a suspicion that the bindings preemptively sink all references and don't handle any floating ones, in order to escape the floating hell. Is that true? That alone would imply a lot of answers regarding ownership handling.

That's correct, yes. Bindings have to sink them correctly though, and that's a bit annoying in special cases :)

> Am I right in understanding that the `from_glib_foo` function family exist primarily to be called immediately as a return value of the corresponding kind is received? I'm asking because I've previously successfully (?) used them to reference preexisting objects across the FFI bounds.

That's correct. A return value (or out parameter) that is `transfer full` gets passed to `from_glib_full()`, etc. Similarly a parameter with `transfer full` goes through `to_glib_full()`.

> Sure, I'll create one.

Thanks :)

**Comment by dcz-purism** [comment]
There's the first draft: https://github.com/gtk-rs/glib/pull/587

**Comment by dcz-purism** [comment]
Explanations merged, I'm no longer confused.
