### ISSUE TITLE
simple examples to define and implement a new GObject in Rust

### ISSUE THREAD

**Issue by derust** [gtk-rs/glib#672]
I am trying to reimplement  [frida-gum-example.c](https://gist.github.com/oleavr/3edc47c9f69eb048de9d70ed45998f9c#file-frida-gum-example-c) in Rust. The core part is  define an gobject instance and implement callback interface use C macros G_DECLARE_FINAL_TYPE and G_DEFINE_TYPE_EXTENDED. 

Since I have no experience on glib before, and GIR seems to be too heave to pick up. 

So I just use direct api from gobject_sys and bindgen to convert C header to rust struct.

The program can compile and run success,   but  will crash occasionally.

This is my code 
[hook_register](https://gist.github.com/derust/f17cbea02c3c7ad329fff66742e1d3a0#file-hook-rs-L47)  

[let HOOK_TYPE = hook::hook_register();](https://gist.github.com/derust/f17cbea02c3c7ad329fff66742e1d3a0#file-main-rs-L22)

Could you help me to check if I miss some init step or do some thing wrong?

It's great if we have a runnable example for such use case. 
Thanks for your great job!

**Comment by sdroege** [comment]
Did you see https://www.figuiere.net/technotes/notes/tn002/, https://github.com/gtk-rs/examples/blob/master/src/bin/basic_subclass.rs, https://github.com/gtk-rs/examples/blob/5d38aff77331b509f141514e309b8e8cd99cffad/src/bin/listbox_model.rs#L206-L342 and https://coaxion.net/blog/2017/09/exporting-a-gobject-c-api-from-rust-code-and-using-it-from-c-python-javascript-and-others/ ?

The latter blog post also does things manually with unsafe code like you do here, but if you check the master version of the repository there it also makes more use of the `glib` crate infrastructure to simplify things.

The recommended way to do GObject subclasses in Rust is how the other links are doing it and the git master code of the last blog post. That code and the listbox model example should be very close to what you want to do here.

Please re-open if you think anything else is missing :)

**Comment by derust** [comment]
Hi sdroege,

Thanks for reply.

It take me some time to read all links in you reply,  especially the listbox_model example, It seems very promising.

But my problem is:  The C  library I want to use  need to implement an interface.

And that interface is defined in C. I can't find a way to implement it in Rust directly.

Currently I get that interface type use call to it's  _get_type function. [gum_invocation_listener_get_type()](https://gist.github.com/derust/f17cbea02c3c7ad329fff66742e1d3a0#file-hook-rs-L68
)

Is it enough? Or I have to define that interface in Rust like you mentioned in the [last link](https://coaxion.net/blog/2017/09/exporting-a-gobject-c-api-from-rust-code-and-using-it-from-c-python-javascript-and-others/#interfaces).

Or I need create a Rust binding for the whole C library use GIR?

Thanks

**Comment by sdroege** [comment]
> Or I need create a Rust binding for the whole C library use GIR?

Well, for the parts that you use this would be an option. I assume you will want to make use of more of the API of that library anyway?

But that's not needed: you can implement the GObject like in the listbox_model example and then inside the `ObjectSubclass::type_init()` function you could go back to calling unsafe code and basically call `gobject_sys::g_type_add_interface_static()` like you did in the code you wrote originally. The `ToGlib::to_glib()` impl on `InitializingType` allows you to get the raw C `GType` in there.

**Comment by sdroege** [comment]
And for getting back from the C functions to the Rust struct of your GObject, take a look at this interface example: https://github.com/gtk-rs/gio/blob/809e580c56f1434327a3c81af49cb75baea5faf7/src/subclass/seekable.rs#L69-L94

**Comment by derust** [comment]
Hi sdroege,
I reimplement the example use ObjectSubclass, but the random crash still happens.
I found it may relate to my cross build settings. cause the crash only happens when I cross build it to Android on Macos.  If I use native build on Macos, everything works fine. I'll dig into it later.
Thanks very much!

**Comment by sdroege** [comment]
Can you provide a backtrace (with debug symbols of all involved libraries) of the crash, and the corresponding code?

**Comment by derust** [comment]
Android logcat output is like [this one](https://gist.github.com/derust/f17cbea02c3c7ad329fff66742e1d3a0#gistcomment-3397449
).
I'm used to be a java programmer,  not familiar with this kind of  problem. I guess it may caused by wrong memory usage between Rust & C.

**Comment by sdroege** [comment]
Looks like memory corruption, yes. Can you put the code of the whole thing somewhere?

**Comment by derust** [comment]
Hi sdroege, sorry for late reply. 
I have create a repo [here](https://github.com/derust/frida-gum-rs)

**Comment by sdroege** [comment]
Why the cast [here](https://github.com/derust/frida-gum-rs/blob/master/src/hook.rs#L73)?

```rust
iface_type_raw as usize,
```

----

Also [this](https://github.com/derust/frida-gum-rs/blob/master/src/main.rs#L24) is wrong:
```rust
        let listener: *mut GumInvocationListener = std::mem::transmute(obj);
```

You don't need the Rust wrapper struct here but the pointer to the C struct. You can get that via `obj.to_glib_none().0` (`use glib::translate::*` first).

----

I don't see anything obviously wrong here otherwise. Running through `valgrind` might help to understand where things go wrong, can you do that?

----

Also I would recommend using gir for generating the `-sys` bindings, not `bindgen`. `bindgen` does not work that well on GObject-based libraries.

`bindgen` also usually generates structs that are platform dependent for the platform where you build things. `gir` creates structs that are platform independent.

Also it looks like you're trying to generate bindings for this library? In that case it would make even more sense to use gir, also for generating the safe part of the bindings (which will still need some manual code here though). It will safe you a lot of time and pain.

**Comment by derust** [comment]
Wow, thanks a lot. 

I use the cast  `iface_type_raw as usize` , because it wont compile otherwise.  
`^^^^^^^^^^^^^^ expected `usize`, found `u64``

when I change my code to `obj.to_glib_none().0` , compiler complains
`^^^^^^^^^^^^ the trait `glib::translate::ToGlibPtr<'_, *mut _GumInvocationListener>` is not implemented for `hook::HookObject`

I'm just want to get my hand's dirty to make something useful in Rust,  I don't have a good understanding of Rust right now(like the pointer things). But it's very funny to learn.
And I will try GIR when I have time.

**Comment by sdroege** [comment]
> I use the cast `iface_type_raw as usize` , because it wont compile otherwise.
> `^^^^^^^^^^^^^^ expected `usize`, found `u64``

That's probably the problem then. `bindgen` making it an `u64` while it actually is a `usize`. On 32 bit platforms this would be the same as a `u32`.

> when I change my code to `obj.to_glib_none().0` , compiler complains
> `^^^^^^^^^^^^ the trait `glib::translate::ToGlibPtr<'_, *mut _GumInvocationListener>`is not implemented for`hook::HookObject`

That's because you don't have proper bindings for that interface yet. You can work around that by doing

```rust
let ptr: *mut gobject_sys::GObject = obj.to_glib_none().0;
let ptr = ptr as *mut _GumInvocationListener;
```
or similar

>  And I will try GIR when I have time.

Let me know if you run into any problems :) At least the -sys generation should be straightforward with gir and should solve this problem here at least. Feel free to also come to our IRC channel for discussing how to use it.
