### ISSUE TITLE
mismatched types

### ISSUE THREAD

**Issue by chessnokov** [gtk-rs/glib#71]
```
.cargo/registry/src/github.com-0a35038f75765ae4/glib-0.0.4/src/signal.rs:12:53: 12:61 error: mismatched types:
 expected `*mut gobject_sys::GObject`,
    found `*mut libc::types::common::c95::c_void`
(expected struct `gobject_sys::GObject`,
    found enum `libc::types::common::c95::c_void`) [E0308]
.cargo/registry/src/github.com-0a35038f75765ae4/glib-0.0.4/src/signal.rs:12     let handle = gobject_ffi::g_signal_connect_data(receiver, signal_name.to_glib_none().0,
                                                                                                                                                 ^~~~~~~~
.cargo/registry/src/github.com-0a35038f75765ae4/glib-0.0.4/src/signal.rs:12:53: 12:61 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `glib`.
```

**Comment by gkoz** [comment]
API mismatches usually happen when the crates are out of sync. `cargo update` or reverting to known good `Cargo.lock` should help.

**Comment by gkoz** [comment]
One possible cause might be if your `glib` crate is pinned at `0.0.4` but is trying to work with `gobject` `0.2.1`. Unpin the `glib` crate then. We're somewhat breaking the semver rules yes...

**Comment by chessnokov** [comment]
remove ~/.cargo/registry
remove Cargo.lock
update Cargo.toml from https://github.com/gtk-rs/examples/blob/master/Cargo.toml
cargo clean
cargo build - work fine

**Comment by GuillaumeGomez** [comment]
I'm not sure it was useful to do:

```Shell
remove ~/.cargo/registry
```

Otherwise, if it's fixed, please close this issue. :)

**Comment by Alittlemurkling** [comment]
I get this error as well, using multirust to build my personal project with the gtk crate:

/home/zap/.multirust/toolchains/stable/cargo/registry/src/github.com-0a35038f75765ae4/glib-0.0.4/src/signal.rs:12:53: 12:61 error: mismatched types:
 expected `*mut gobject_sys::GObject`,
    found `*mut libc::types::common::c95::c_void`
(expected struct `gobject_sys::GObject`,
    found enum `libc::types::common::c95::c_void`) [E0308]
/home/zap/.multirust/toolchains/stable/cargo/registry/src/github.com-0a35038f75765ae4/glib-0.0.4/src/signal.rs:12     let handle = gobject_ffi::g_signal_connect_data(receiver, signal_name.to_glib_none().0,
                                                                                                                                                                      ^~~~~~~~
/home/zap/.multirust/toolchains/stable/cargo/registry/src/github.com-0a35038f75765ae4/glib-0.0.4/src/signal.rs:12:53: 12:61 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to previous error
Build failed, waiting for other jobs to finish...
Could not compile `glib`.

The steps to fix it do not work for me however. I have tried removing my multirust directory completely. Strangely, I can actually build the latest gtk from source.

**Comment by gkoz** [comment]
You don't have to remove anything. Showing the relevant `Cargo.toml` and whether you've run `cargo update` might help though.

**Comment by Alittlemurkling** [comment]
I ran `cargo update` and the error persists. This is my Cargo.toml:
    [package]
    name = "rfm"
    version = "0.0.1"
    authors = ["zap"]

    [dependencies]
    gtk = "0.0.4"

**Comment by gkoz** [comment]
Yeah, this effectively pins `gtk` to `0.0.4` because 0.0.x versions are considered semver-incompatible. So if you change that to `0.0.5` I expect everything to build nicely again. Alternatively downgrade the sys crates like this:
```
cargo update -p glib-sys --precise 0.2.0
cargo update -p gobject-sys --precise 0.2.0
...
```

--
I'll try to be more careful with respect to semver next time.

**Comment by Alittlemurkling** [comment]
That solved it. I did not realize there was a new version. Thank you.

**Comment by GuillaumeGomez** [comment]
So I guess we can close it now. Please notify me if it does need to be reopened.
